import {getSession,onAuthChange,signIn,signOut,resetPassword} from './auth/auth.js';import {getAll,get,post} from './core/api.js';import {getState,setData,setLoading,setError,clearData,setSession} from './core/state.js';import {renderShell,renderAuth} from './components/shell.js';import {loading,errorState,toast} from './components/ui.js';import {renderDashboard} from './modules/dashboard/dashboard.js';import {renderCustomers} from './modules/customers/customers.js';import {renderWebsites} from './modules/websites/websites.js';import {renderTasks} from './modules/tasks/tasks.js';import {renderContacts} from './modules/contacts/contacts.js';import {renderServices} from './modules/services/services.js';import {renderCustomerServices} from './modules/customer-services/customer-services.js';import {renderTeam} from './modules/team/team.js';import {renderMaintenance} from './modules/maintenance/maintenance.js';import {renderHealth} from './modules/health/health.js';import {renderActivity} from './modules/activity/activity.js';import {renderReports} from './modules/reports/reports.js';import {renderSettings} from './modules/settings/settings.js';
const routes={dashboard:['Dashboard',renderDashboard],customers:['Customers',renderCustomers],websites:['Websites',renderWebsites],tasks:['Tasks',renderTasks],contacts:['Contacts',renderContacts],services:['Services',renderServices],['customer-services']:['Customer Services',renderCustomerServices],team:['Team',renderTeam],maintenance:['Maintenance',renderMaintenance],health:['Website Health',renderHealth],activity:['Activity Log',renderActivity],reports:['Reports',renderReports],settings:['Settings',renderSettings]};
let rendering=false;
function mountAuth(){const app=document.getElementById('app');app.innerHTML=renderAuth();const form=document.getElementById('login-form');form.addEventListener('submit',async e=>{e.preventDefault();const msg=document.getElementById('auth-message'),btn=form.querySelector('button[type=submit]');const fd=new FormData(form);btn.disabled=true;btn.textContent='Signing in…';msg.textContent='';try{await signIn(fd.get('email'),fd.get('password'));}catch(err){msg.textContent=err.message||'Unable to sign in.';msg.className='auth-message error';btn.disabled=false;btn.textContent='Sign in'}});document.getElementById('forgot-password').addEventListener('click',async()=>{const email=form.elements.email.value.trim(),msg=document.getElementById('auth-message');if(!email){msg.textContent='Enter your email first.';msg.className='auth-message error';return}try{await resetPassword(email);msg.textContent='Password reset instructions sent.';msg.className='auth-message success-msg'}catch(e){msg.textContent=e.message;msg.className='auth-message error'}})}
function mountShell(){document.getElementById('app').innerHTML=renderShell();document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));document.getElementById('mobile-menu').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));document.getElementById('sign-out').addEventListener('click',async()=>{try{await signOut()}catch(e){toast(e.message,'error')}});document.getElementById('refresh-top').addEventListener('click',()=>reload(true));const email=getState().session?.user?.email||'';document.getElementById('avatar').textContent=(email[0]||'W').toUpperCase();}
async function load(){setLoading(true);setError(null);try{setData(await getAll())}catch(e){setError(e);throw e}finally{setLoading(false)}}
async function navigate(route){if(!getState().session)return;if(!routes[route])route='dashboard';if(rendering)return;rendering=true;const [title,renderer]=routes[route];document.getElementById('page-title').textContent=title;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===route));document.getElementById('sidebar')?.classList.remove('open');if(location.hash!==`#${route}`)history.replaceState(null,'',`#${route}`);const content=document.getElementById('content');if(!getState().loaded)content.innerHTML=loading('Loading CRM data…');try{content.innerHTML=await renderer();}catch(e){console.error(e);content.innerHTML=errorState(e.message||'Unable to render this page.')}finally{rendering=false}}
async function reload(showToast=false){try{await load();await navigate(location.hash.slice(1)||'dashboard');if(showToast)toast('CRM data refreshed','success')}catch(e){document.getElementById('content').innerHTML=errorState(`CRM connection failed: ${e.message}`)}}
async function boot(session){setSession(session);if(!session){clearData();mountAuth();return}mountShell();document.getElementById('content').innerHTML=loading('Connecting to CRM…');try{await load();await navigate(location.hash.slice(1)||'dashboard')}catch(e){document.getElementById('content').innerHTML=errorState(`CRM connection failed: ${e.message}`)}}
window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)||'dashboard'));window.addEventListener('portal:reload',()=>reload());
getSession().then(boot).catch(e=>{console.error(e);mountAuth()});onAuthChange(s=>{if(s?.access_token!==getState().session?.access_token||(!s&&getState().session))boot(s)});
