/** Webcraft Operations Portal API
 * Replace the existing 13_API.gs with this file after backing it up.
 * Keeps Google Sheets as the CRM store and exposes CRUD/actions for the portal.
 * Existing automation files (07_*, 08_*, 10_*, 12_*) remain in the Apps Script project.
 */
const PORTAL_API={
  Customers:{id:'Customer ID',prefix:'CUST'},
  Websites:{id:'Website ID',prefix:'WEB'},
  Tasks:{id:'Task ID',prefix:'TASK'},
  Contacts:{id:'Contact ID',prefix:'CON'},
  Services:{id:'Service ID',prefix:'SERV'},
  'Customer Services':{id:'Customer Service ID',prefix:'CS'},
  Team:{id:'Team Member ID',prefix:'TEAM'}
};
const PORTAL_READ={customers:'Customers',websites:'Websites',tasks:'Tasks',contacts:'Contacts',services:'Services','customer-services':'Customer Services',team:'Team',activity:'Activity Log'};
function doGet(e){try{const a=String(e?.parameter?.action||'dashboard').toLowerCase();if(a==='dashboard')return json_({success:true,data:getPortalDashboard_()});const s=PORTAL_READ[a];if(!s)throw new Error('Unknown GET action: '+a);return json_({success:true,data:getPortalRecords_(s)});}catch(err){return json_({success:false,error:err.message||String(err)});}}
function doPost(e){try{const p=parseBody_(e),a=String(p.action||'').toLowerCase();let data;if(a==='create-record')data=createPortalRecord_(p.sheet,p.record);else if(a==='update-record')data=updatePortalRecord_(p.sheet,p.id,p.record);else if(a==='archive-record')data=archivePortalRecord_(p.sheet,p.id);else if(a==='create-customer')data=createPortalRecord_('Customers',p.customer);else if(a==='update-customer')data=updatePortalRecord_('Customers',p.customerId,p.customer);else if(a==='archive-customer')data=archivePortalRecord_('Customers',p.customerId);else if(a==='check-website-health')data=checkAllWebsiteHealth_();else if(a==='recalculate-maintenance')data=recalculateAllPortalMaintenance_();else throw new Error('Unknown POST action: '+a);return json_({success:true,data});}catch(err){return json_({success:false,error:err.message||String(err)});}}
function parseBody_(e){if(!e||!e.postData||!e.postData.contents)throw new Error('Missing request body');try{return JSON.parse(e.postData.contents)}catch(err){throw new Error('Request body must be valid JSON')}}
function json_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON)}
function ss_(){return SpreadsheetApp.getActiveSpreadsheet()}
function sheet_(name){const s=ss_().getSheetByName(name);if(!s)throw new Error('Sheet not found: '+name);return s}
function headers_(s){return s.getRange(1,1,1,s.getLastColumn()).getValues()[0].map(String)}
function records_(name){const s=sheet_(name),h=headers_(s),last=s.getLastRow();if(last<2)return [];const values=s.getRange(2,1,last-1,h.length).getValues();return values.map(r=>Object.fromEntries(h.map((k,i)=>[k,serialize_(r[i])])))}
function getPortalRecords_(name){return records_(name)}
function serialize_(v){if(v instanceof Date)return v.toISOString();return v}
function getPortalDashboard_(){return{customers:records_('Customers'),websites:records_('Websites'),tasks:records_('Tasks')}}
function col_(h,k){const i=h.indexOf(k);if(i<0)throw new Error(`Column not found: ${k}`);return i}
function clean_(v){return v===undefined||v===null?'':String(v).trim()}
function norm_(v){return clean_(v).toLowerCase()}
function idConfig_(sheet){const c=PORTAL_API[sheet];if(!c)throw new Error('CRUD is not enabled for '+sheet);return c}
function rowForId_(s,idField,id){const h=headers_(s),idx=col_(h,idField),last=s.getLastRow();if(last<2)return -1;const vals=s.getRange(2,idx+1,last-1,1).getDisplayValues().flat();const n=norm_(id);for(let i=0;i<vals.length;i++)if(norm_(vals[i])===n)return i+2;return -1}
function nextId_(sheet){const cfg=idConfig_(sheet),s=sheet_(sheet),h=headers_(s),last=s.getLastRow();if(last<2)return cfg.prefix+'-001';const idx=col_(h,cfg.id),vals=s.getRange(2,idx+1,last-1,1).getDisplayValues().flat();let max=0;vals.forEach(v=>{const m=String(v).match(new RegExp('^'+cfg.prefix+'-(\\d+)$','i'));if(m)max=Math.max(max,Number(m[1]))});return cfg.prefix+'-'+String(max+1).padStart(3,'0')}
function unique_(sheet,field,value,ignoreIdField,ignoreId){const s=sheet_(sheet),h=headers_(s),last=s.getLastRow();if(last<2)return;const idx=col_(h,field),idIdx=ignoreIdField?h.indexOf(ignoreIdField):-1;const vals=s.getRange(2,1,last-1,h.length).getValues();for(let i=0;i<vals.length;i++){if(ignoreId&&idIdx>=0&&norm_(vals[i][idIdx])===norm_(ignoreId))continue;if(norm_(vals[i][idx])===norm_(value)&&norm_(value))throw new Error(`${field} already exists: ${value}`)}}
function validateRelations_(sheet,record){if(sheet==='Websites'&&clean_(record['Customer ID'])&&!rowForId_(sheet_('Customers'),'Customer ID',record['Customer ID']))throw new Error('Customer ID does not exist.');if(sheet==='Tasks'){if(clean_(record['Customer ID'])&&!rowForId_(sheet_('Customers'),'Customer ID',record['Customer ID']))throw new Error('Task Customer ID does not exist.');if(clean_(record['Website ID'])&&!rowForId_(sheet_('Websites'),'Website ID',record['Website ID']))throw new Error('Task Website ID does not exist.')}if(sheet==='Contacts'&&clean_(record['Customer ID'])&&!rowForId_(sheet_('Customers'),'Customer ID',record['Customer ID']))throw new Error('Contact Customer ID does not exist.');if(sheet==='Customer Services'){if(clean_(record['Customer ID'])&&!rowForId_(sheet_('Customers'),'Customer ID',record['Customer ID']))throw new Error('Customer Service Customer ID does not exist.');if(clean_(record['Service ID'])&&!rowForId_(sheet_('Services'),'Service ID',record['Service ID']))throw new Error('Customer Service Service ID does not exist.')}}
function enrich_(sheet,record){const r={};Object.keys(record||{}).forEach(k=>r[k]=record[k]);if(sheet==='Websites'&&clean_(r['Customer ID'])){const row=getById_('Customers','Customer ID',r['Customer ID']);r['Company Name']=row?.['Company Name']||r['Company Name']||''}if(sheet==='Tasks'){if(clean_(r['Customer ID'])){const c=getById_('Customers','Customer ID',r['Customer ID']);r['Company Name']=c?.['Company Name']||r['Company Name']||''}}if(sheet==='Customer Services'){if(clean_(r['Customer ID'])){const c=getById_('Customers','Customer ID',r['Customer ID']);r['Company Name']=c?.['Company Name']||r['Company Name']||''}if(clean_(r['Service ID'])){const s=getById_('Services','Service ID',r['Service ID']);r['Service Name']=s?.['Service Name']||r['Service Name']||''}}return r}
function getById_(sheet,idField,id){const s=sheet_(sheet),h=headers_(s),row=rowForId_(s,idField,id);if(row<0)return null;const vals=s.getRange(row,1,1,h.length).getValues()[0];return Object.fromEntries(h.map((k,i)=>[k,serialize_(vals[i])]));}
function writeRecord_(sheet,record,isUpdate){const s=sheet_(sheet),h=headers_(s);const cfg=idConfig_(sheet);const data=enrich_(sheet,record||{});if(!isUpdate)data[cfg.id]=nextId_(sheet);const row=isUpdate?rowForId_(s,cfg.id,record.__id):s.getLastRow()+1;const old=isUpdate?s.getRange(row,1,1,h.length).getValues()[0]:Array(h.length).fill('');const out=h.map((k,i)=>Object.prototype.hasOwnProperty.call(data,k)?coerce_(data[k],old[i]):old[i]);s.getRange(row,1,1,h.length).setValues([out]);return getById_(sheet,cfg.id,data[cfg.id]||record.__id)}
function coerce_(v,old){if(v===''||v===null||v===undefined)return '';if(old instanceof Date&&typeof v==='string'&&/^\d{4}-\d{2}-\d{2}/.test(v)){const d=new Date(v);return Number.isNaN(d.getTime())?v:d}return v}
function createPortalRecord_(sheet,record){const cfg=idConfig_(sheet),r={...(record||{})};delete r.__id;validateRelations_(sheet,r);if(clean_(r[cfg.id])){if(rowForId_(sheet_(sheet),cfg.id,r[cfg.id])>0)throw new Error(`${cfg.id} already exists.`)}if(sheet==='Websites'&&clean_(r.Domain))unique_('Websites','Domain',r.Domain);const created=writeRecord_(sheet,r,false);logPortal_('INFO','CREATE',sheet,cfg.id,created[cfg.id],'Record created');syncLists_();return created}
function updatePortalRecord_(sheet,id,record){const cfg=idConfig_(sheet),s=sheet_(sheet),row=rowForId_(s,cfg.id,id);if(row<0)throw new Error(`${cfg.id} not found: ${id}`);const current=getById_(sheet,cfg.id,id),merged={...current,...(record||{}),__id:id};validateRelations_(sheet,merged);if(sheet==='Websites'&&norm_(merged.Domain)!==norm_(current.Domain))unique_('Websites','Domain',merged.Domain,cfg.id,id);const updated=writeRecord_(sheet,merged,true);logChanges_(sheet,current,updated);syncLists_();return updated}
function archivePortalRecord_(sheet,id){const cfg=idConfig_(sheet),s=sheet_(sheet),row=rowForId_(s,cfg.id,id);if(row<0)throw new Error(`${cfg.id} not found: ${id}`);const h=headers_(s),statusIdx=h.indexOf('Status');if(statusIdx<0)throw new Error('This record has no Status column.');const old=s.getRange(row,statusIdx+1).getDisplayValue();s.getRange(row,statusIdx+1).setValue('Archived');logPortal_('INFO','ARCHIVE',sheet,cfg.id,id,`Status changed from ${old||'blank'} to Archived`);syncLists_();return getById_(sheet,cfg.id,id)}
function logChanges_(sheet,oldR,newR){const tracked={Customers:['Company Name','Customer Type','Primary Contact','Email','Phone','Status','Plan','Billing Cycle','Account Manager','Notes'],Websites:['Company Name','Domain','Website Name','Status','Website Type','Hosting Provider','Production URL','Repository','Assigned Developer','Notes'],Tasks:['Task Title','Assigned To','Priority','Status','Due Date','Completed Date','Notes']};(tracked[sheet]||[]).forEach(k=>{if(norm_(oldR?.[k])!==norm_(newR?.[k]))logPortal_('INFO','UPDATE',sheet,PORTAL_API[sheet].id,newR[PORTAL_API[sheet].id],`${k} changed` ,k,oldR?.[k],newR?.[k])})}
function logPortal_(level,action,module,idField,id,message,field,oldV,newV){try{if(typeof logActivity_==='function')logActivity_({level,action,module,recordType:module,recordId:id,field:field||'',oldValue:oldV??'',newValue:newV??'',message,source:'Portal API'})}catch(e){console.log(e)}}
function syncLists_(){try{if(typeof syncLists==='function')syncLists()}catch(e){console.log(e)}}
function checkAllWebsiteHealth_(){const s=sheet_('Websites'),h=headers_(s),last=s.getLastRow();if(last<2)return{checked:0};const idx={id:col_(h,'Website ID'),url:h.indexOf('Production URL'),last:col_(h,'Last Health Check'),health:col_(h,'Website Health'),http:col_(h,'HTTP Status'),ms:col_(h,'Response Time (ms)'),https:col_(h,'HTTPS Status')};let checked=0;for(let r=2;r<=last;r++){const id=s.getRange(r,idx.id+1).getDisplayValue(),url=idx.url>=0?s.getRange(r,idx.url+1).getDisplayValue():'';if(!id||!url)continue;const started=Date.now();let health='Offline',code='',https=String(url).toLowerCase().startsWith('https://')?'HTTPS':'Not HTTPS';try{const res=UrlFetchApp.fetch(url,{muteHttpExceptions:true,followRedirects:true});code=res.getResponseCode();health=code>=200&&code<400?'Online':'Problem'}catch(e){code='ERR'}const ms=Date.now()-started;s.getRange(r,idx.last+1).setValue(new Date());s.getRange(r,idx.health+1).setValue(health);s.getRange(r,idx.http+1).setValue(code);s.getRange(r,idx.ms+1).setValue(ms);s.getRange(r,idx.https+1).setValue(https);checked++;logPortal_('INFO','HEALTH_CHECK','Websites','Website ID',id,`${health} (${code}) in ${ms} ms`)}return{checked}}
function recalculateAllPortalMaintenance_(){const s=sheet_('Websites'),h=headers_(s),last=s.getLastRow();if(last<2)return{updated:0};const p=h.indexOf('Last Maintenance'),q=h.indexOf('Next Maintenance'),ab=h.indexOf('Maintenance Health');if(p<0||q<0||ab<0)throw new Error('Maintenance columns are missing.');let updated=0;for(let r=2;r<=last;r++){const lastM=s.getRange(r,p+1).getValue();if(!(lastM instanceof Date)){s.getRange(r,q+1).clearContent();s.getRange(r,ab+1).setValue('Not Scheduled');continue}const next=new Date(lastM);next.setDate(next.getDate()+30);const today=new Date();today.setHours(0,0,0,0);const nd=new Date(next);nd.setHours(0,0,0,0);const diff=Math.ceil((nd-today)/86400000);const status=diff<0?'Overdue':diff<=7?'Due Soon':'Scheduled';s.getRange(r,q+1).setValue(next);s.getRange(r,ab+1).setValue(status);updated++}return{updated}}
