import {esc} from '../core/utils.js';
export const loading=m=>`<div class="state-card"><div class="spinner"></div><h3>${esc(m||'Loading…')}</h3><p>Please wait.</p></div>`;
export const errorState=m=>`<div class="state-card error"><h3>Something went wrong</h3><p>${esc(m)}</p><button class="btn primary" data-action="refresh">Retry</button></div>`;
export const empty=m=>`<div class="empty-state"><div class="empty-icon">○</div><strong>${esc(m||'No records found')}</strong><span>Try changing your filters or add a new record.</span></div>`;
export function toast(m,type='info'){let e=document.getElementById('toast');if(!e){e=document.createElement('div');e.id='toast';document.body.appendChild(e)}e.textContent=m;e.className=`toast show ${type}`;clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3500)}
export function modal({title,body,actions=''}){document.getElementById('modal-root')?.remove();const r=document.createElement('div');r.id='modal-root';r.innerHTML=`<div class="modal-backdrop" data-close><div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><h3>${esc(title)}</h3><button class="icon-button" data-close>×</button></div><div class="modal-body">${body}</div><div class="modal-actions">${actions}</div></div></div>`;document.body.appendChild(r);r.addEventListener('click',e=>{if(e.target.closest('[data-close]'))r.remove()});return r}
export const confirmAction=(title,message,onYes)=>modal({title,body:`<p>${esc(message)}</p>`,actions:`<button class="btn" data-close>Cancel</button><button class="btn danger-btn" id="confirm-yes">Confirm</button>`}) && document.getElementById('confirm-yes').addEventListener('click',()=>{document.getElementById('modal-root')?.remove();onYes()});
export function formField(label,name,value='',type='text',extra=''){return `<label class="field"><span>${esc(label)}</span><input name="${esc(name)}" type="${type}" value="${esc(value??'')}" ${extra}></label>`}
export function textarea(label,name,value=''){return `<label class="field full"><span>${esc(label)}</span><textarea name="${esc(name)}">${esc(value??'')}</textarea></label>`}
export function selectField(label,name,options,current=''){return `<label class="field"><span>${esc(label)}</span><select name="${esc(name)}">${options}</select></label>`}
export const tableShell=(head,body)=>`<div class="card table-card"><div class="table-wrap"><table><thead>${head}</thead><tbody>${body}</tbody></table></div></div>`;
